# Generated by Django 4.2.6 on 2024-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file_format',
            field=models.CharField(max_length=20, null=True, verbose_name='Format'),
        ),
    ]
