# Generated by Django 4.2.6 on 2024-07-26 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('File', '0002_remove_filemodel_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
