# Generated by Django 4.2.6 on 2024-07-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_alter_filemodel_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='num_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
