# Generated by Django 4.2.6 on 2024-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0004_filemodel_num_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file_format',
            field=models.CharField(default='pdf', max_length=20, null=True, verbose_name='Format'),
        ),
    ]
