# Generated by Django 4.2.6 on 2024-09-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0005_alter_filemodel_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='trash',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
