# Generated by Django 4.2.6 on 2024-08-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='profile_image',
        ),
    ]
