# Generated by Django 4.2.6 on 2024-09-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('File', '0005_alter_filemodel_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convert_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item_id', models.CharField(max_length=200, null=True)),
                ('converted_file', models.FileField(upload_to='files/converted_files/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='File.filemodel', verbose_name='File')),
            ],
        ),
    ]
