# Generated by Django 4.2.6 on 2024-09-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionmodel',
            name='file',
        ),
        migrations.RemoveField(
            model_name='conversionmodel',
            name='item_id',
        ),
        migrations.AddField(
            model_name='conversionmodel',
            name='original_file',
            field=models.FileField(default=1, upload_to='files/original_files/'),
            preserve_default=False,
        ),
    ]
