# Generated by Django 4.2.6 on 2024-09-06 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversion', '0003_alter_conversionmodel_convert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionmodel',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
