services:
  web:
    build: .
    image: web_ezpdf:latest
    container_name: django_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./logs:/app/logs
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 1G 
          cpus: "1.0" 
        reservations:
          memory: 1G  
          cpus: "0.5" 
    ports:
      - "8000:8000"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "python manage.py migrate &&
        python manage.py shell < create_superuser.py &&
        python manage.py runserver 0.0.0.0:8000"
