# Generated by Django 4.2.6 on 2024-07-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('File', '0004_filemodel_num_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='Page Number')),
                ('tool_type', models.CharField(default='Draw', max_length=20, verbose_name='Tool Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.CharField(max_length=500, verbose_name='Content')),
                ('color', models.CharField(max_length=20, verbose_name='Text Color')),
                ('coord_in_canvas_X', models.FloatField(verbose_name='Canvas X Coordinate')),
                ('coord_in_canvas_Y', models.FloatField(verbose_name='Canvas Y Coordinate')),
                ('coord_in_doc_X', models.FloatField(verbose_name='Document X Coordinate')),
                ('coord_in_doc_Y', models.FloatField(verbose_name='Document Y Coordinate')),
                ('font_size', models.FloatField(default=12, verbose_name='Font Size')),
                ('bold', models.BooleanField(default=False, verbose_name='Bold')),
                ('italic', models.BooleanField(default=False, verbose_name='Italic')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='File.filemodel', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='Page Number')),
                ('tool_type', models.CharField(default='Draw', max_length=20, verbose_name='Tool Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('coordinates', models.TextField(verbose_name='Coordinates')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='File.filemodel', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
