# Generated by Django 4.2.6 on 2024-07-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawmodel',
            name='item_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='textmodel',
            name='item_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
