# Generated by Django 4.2.6 on 2024-08-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_imagemodel_geometrymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='canvas_id',
            field=models.IntegerField(null=True, verbose_name='Image in st.canvas:'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images/images_added/'),
        ),
    ]
