# Generated by Django 4.2.6 on 2024-08-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_imagemodel_canvas_id_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='canvas_id',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='canvas',
            field=models.CharField(max_length=200, null=True, verbose_name='Image in canvas:'),
        ),
    ]
