# Generated by Django 4.2.6 on 2024-08-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_remove_imagemodel_canvas'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='canvas_id',
            field=models.IntegerField(null=True, verbose_name='Image in st.canvas:'),
        ),
    ]
