# Generated by Django 4.2.6 on 2024-08-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_alter_drawmodel_tool_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geometrymodel',
            name='borderradius',
            field=models.CharField(max_length=20, null=True, verbose_name='Radius'),
        ),
        migrations.AddField(
            model_name='geometrymodel',
            name='canvas_id',
            field=models.IntegerField(null=True, verbose_name='Shape in st.canvas:'),
        ),
    ]
