# Generated by Django 4.2.6 on 2024-08-05 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0005_alter_filemodel_file_format'),
        ('tools', '0009_geometrymodel_borderradius_geometrymodel_canvas_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='Page Number')),
                ('tool_type', models.CharField(max_length=20, null=True, verbose_name='Tool Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('item_id', models.CharField(max_length=200, null=True)),
                ('coord_in_canvas_X', models.FloatField(verbose_name='Canvas X Coordinate')),
                ('coord_in_canvas_Y', models.FloatField(verbose_name='Canvas Y Coordinate')),
                ('coord_in_doc_X', models.FloatField(verbose_name='Document X Coordinate')),
                ('coord_in_doc_Y', models.FloatField(verbose_name='Document Y Coordinate')),
                ('height', models.FloatField(verbose_name='Geometry height')),
                ('width', models.FloatField(verbose_name='Geometry width')),
                ('color', models.CharField(max_length=20)),
                ('borderradius', models.CharField(max_length=20, null=True, verbose_name='Radius')),
                ('canvas_id', models.IntegerField(null=True, verbose_name='Shape in st.canvas:')),
                ('shapetype', models.CharField(max_length=50, null=True, verbose_name='Type of shape')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='File.filemodel', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GeometryModel',
        ),
    ]
