# Generated by Django 4.2.6 on 2024-08-05 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_shapemodel_delete_geometrymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapemodel',
            old_name='borderradius',
            new_name='borderRadius',
        ),
        migrations.RenameField(
            model_name='shapemodel',
            old_name='shapetype',
            new_name='shapeType',
        ),
    ]
