# Generated by Django 4.2.6 on 2024-08-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_rename_borderradius_shapemodel_borderradius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawmodel',
            name='coordinates',
            field=models.JSONField(null=True, verbose_name='Coordinates'),
        ),
    ]
