# Generated by Django 4.2.6 on 2024-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_drawmodel_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodel',
            name='font_family',
            field=models.CharField(max_length=100, null=True, verbose_name='Font Text'),
        ),
    ]
