# Generated by Django 4.2.6 on 2024-08-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_alter_drawmodel_tool_type_alter_imagemodel_tool_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmodel',
            name='coord_in_doc_X',
        ),
        migrations.RemoveField(
            model_name='textmodel',
            name='coord_in_doc_Y',
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='priority',
            field=models.IntegerField(null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='priority',
            field=models.IntegerField(null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='shapemodel',
            name='priority',
            field=models.IntegerField(null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='textmodel',
            name='priority',
            field=models.IntegerField(null=True, verbose_name='Priority'),
        ),
        migrations.AddConstraint(
            model_name='drawmodel',
            constraint=models.UniqueConstraint(fields=('file', 'priority'), name='unique_draw_priority'),
        ),
        migrations.AddConstraint(
            model_name='imagemodel',
            constraint=models.UniqueConstraint(fields=('file', 'priority'), name='unique_image_priority'),
        ),
        migrations.AddConstraint(
            model_name='shapemodel',
            constraint=models.UniqueConstraint(fields=('file', 'priority'), name='unique_shape_priority'),
        ),
        migrations.AddConstraint(
            model_name='textmodel',
            constraint=models.UniqueConstraint(fields=('file', 'priority'), name='unique_text_priority'),
        ),
    ]
