# Generated by Django 4.2.6 on 2024-08-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0019_remove_imagemodel_canvas_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapemodel',
            name='canvas_id',
        ),
        migrations.RemoveField(
            model_name='shapemodel',
            name='coord_in_doc_X',
        ),
        migrations.RemoveField(
            model_name='shapemodel',
            name='coord_in_doc_Y',
        ),
        migrations.AlterField(
            model_name='shapemodel',
            name='height',
            field=models.FloatField(verbose_name='Shape height'),
        ),
        migrations.AlterField(
            model_name='shapemodel',
            name='width',
            field=models.FloatField(verbose_name='Shape width'),
        ),
    ]
