# Generated by Django 4.2.6 on 2024-08-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_remove_shapemodel_canvas_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapemodel',
            old_name='borderRadius',
            new_name='radius',
        ),
    ]
