# Generated by Django 4.2.6 on 2024-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0021_rename_borderradius_shapemodel_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='radius',
            field=models.CharField(default=0, max_length=20, null=True, verbose_name='Radius'),
        ),
        migrations.AlterField(
            model_name='shapemodel',
            name='shapeType',
            field=models.FloatField(max_length=50, null=True, verbose_name='Type of shape'),
        ),
    ]
