# Generated by Django 4.2.6 on 2024-08-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0022_alter_shapemodel_radius_alter_shapemodel_shapetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shapemodel',
            old_name='shapeType',
            new_name='shape_type',
        ),
    ]
