# Generated by Django 4.2.6 on 2024-08-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0023_rename_shapetype_shapemodel_shape_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapemodel',
            name='shape_type',
            field=models.CharField(max_length=50, null=True, verbose_name='Type of shape'),
        ),
    ]
