# Generated by Django 4.2.6 on 2024-08-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0024_alter_shapemodel_shape_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawmodel',
            old_name='coordinates',
            new_name='path_coordinates',
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Line Color'),
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='coord_in_canvas_X',
            field=models.FloatField(null=True, verbose_name='Canvas X Coordinate'),
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='coord_in_canvas_Y',
            field=models.FloatField(null=True, verbose_name='Canvas Y Coordinate'),
        ),
        migrations.AddField(
            model_name='drawmodel',
            name='width',
            field=models.FloatField(null=True, verbose_name='Line width'),
        ),
    ]
