





















# name: CI/CD Pipeline

# on:
#   workflow_dispatch:
#     inputs:
#       action:
#         description: 'Select action to perform'
#         required: true
#         default: 'build'
#         type: choice
#         options:
#           - build
#           - test
#           - deploy

# jobs:
#   build:
#     if: ${{ github.event.inputs.action == 'build' }}
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Build Docker image
#         run: |
#           docker build -t your-dockerhub-username/your-image-name:latest .

#   test:
#     if: ${{ github.event.inputs.action == 'test' }}
#     runs-on: ubuntu-latest
#     needs: build  # Đảm bảo bước test chỉ chạy sau khi build thành công
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       - name: Run tests
#         run: |
#           # Run your tests here
#           echo "Running tests..."

#   deploy:
#     if: ${{ github.event.inputs.action == 'deploy' }}
#     runs-on: ubuntu-latest
#     needs: test  # Đảm bảo bước deploy chỉ chạy sau khi test thành công
#     steps:
#       - name: SSH into Server and deploy
#         uses: appleboy/ssh-action@v0.1.6
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             cd /path/to/your/repository
#             git pull origin main
#             docker-compose down
#             docker-compose up -d
