name: CI/CD Pipeline  # Tên workflow

on:
  workflow_dispatch:  # Kích hoạt workflow thủ công
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - run-all
          - rollback  # Tùy chọn rollback
      ref:  # Thêm input để chọn branch hoặc tag
        description: 'Select branch or tag to run the workflow'
        required: true
        default: 'main'

jobs:
  # Job 'build': Xây dựng Docker image
  build:
    # Điều kiện chạy job này:
    # - Phải là nhánh 'main' hoặc tag bắt đầu với 'v'
    # - Phải chọn action là 'run-all' hoặc 'build'
    if: >
      (github.event.inputs.action == 'run-all' || github.event.inputs.action == 'build') &&
      (startsWith(github.event.inputs.ref, 'refs/heads/main') || startsWith(github.event.inputs.ref, 'refs/tags/v'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}  # Sử dụng branch hoặc tag được chọn

      - name: Print action and ref
        run: |
          echo "Selected action: ${{ github.event.inputs.action }}"
          echo "Selected ref: ${{ github.event.inputs.ref }}"
