name: CI/CD Pipeline  # Tên workflow

on:
  workflow_dispatch:  # Kích hoạt workflow thủ công
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - run-all
          - rollback  # Tùy chọn rollback
      ref:  # Thêm selection để chọn branch hoặc tag
        description: 'Select branch or tag to run the workflow'
        required: true
        type: choice
        options:  # Danh sách các branch hoặc tag có thể chọn
          - refs/heads/main  # Nhánh main
          - refs/heads/develop  # Nhánh develop
          - refs/tags/v1.0.0  # Tag phiên bản 1.0.0
          - refs/tags/v1.1.0  # Tag phiên bản 1.1.0

jobs:
  # Job 'build': Xây dựng Docker image
  build:
    if: >
      (github.event.inputs.action == 'run-all' || github.event.inputs.action == 'build') &&
      (startsWith(github.event.inputs.ref, 'refs/heads/') || startsWith(github.event.inputs.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Print action and ref
        run: |
          echo "Selected action: ${{ github.event.inputs.action }}"
          echo "Selected ref: ${{ github.event.inputs.ref }}"
