name: CI/CD Pipeline  # Tên workflow

on:
  workflow_dispatch:  # Kích hoạt workflow thủ công
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - run-all
          - rollback  # Tùy chọn rollback

jobs:
  # Job 'build': Xây dựng Docker image
  build:
    if: ${{ github.event.inputs.action == 'run-all' || github.event.inputs.action == 'build' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y_%m_%d_%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t nhothoang/webezpdf:lasttest .

      - name: Push Docker image to DockerHub
        run: |
          docker push nhothoang/webezpdf:lasttest
  # Job 'test': Chạy các bài kiểm tra
  test:
    if: ${{ github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          # Thêm lệnh kiểm tra thực tế tại đây

  # Job 'deploy': Triển khai ứng dụng
  deploy:
    if: ${{ github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem  # Đặt quyền chỉ đọc cho file key

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key_path: ec2-key.pem
          script: |
            set -e
            echo "Logging into DockerHub..."
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            
            # echo "Getting the latest Docker image tag..."
            # # Liệt kê tất cả tags của hình ảnh từ DockerHub và lấy tag mới nhất
            # latest_tag=$(curl -s "https://hub.docker.com/v2/repositories/nhothoang/webezpdf/tags" | jq -r '.results[0].name')
            # echo "Latest image tag: $latest_tag"

            echo "Pulling the latest Docker image..."
            docker pull nhothoang/webezpdf:lasttest
            
            echo "Pulling latest changes from Git repository..."
            # Kiểm tra xem thư mục /app có tồn tại không
            if [ ! -d "/home/ubuntu/app" ]; then
              echo "Thư mục /home/ubuntu/app không tồn tại, tạo mới..."
              sudo mkdir /home/ubuntu/app
            else
              echo "Thư mục /home/ubuntu/app đã tồn tại."
            fi

            # Di chuyển vào thư mục /app
            cd /home/ubuntu/app
            git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/Group-Multi-Projects/EzPDF.git
            git pull origin main
            
            echo "Shutting down existing containers and removing images..."
            docker-compose down --rmi all
            
            echo "Starting containers with the latest image..."
            docker-compose up -d
            
            echo "Deployment completed!"

  # Job 'rollback': Khôi phục phiên bản trước
  rollback:
    if: ${{ github.event.inputs.action == 'rollback' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server for Rollback
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Rolling back to previous version..."
            
            # Lấy tag của phiên bản trước
            PREVIOUS_TAG=$(docker images your-dockerhub-username/your-image-name --format '{{.Tag}}' | tail -n 2 | head -n 1)
            
            # Kiểm tra phiên bản trước
            if [ -z "$PREVIOUS_TAG" ]; then
              echo "No previous version found. Rollback failed!"
              exit 1
            fi
            
            echo "Found previous version: $PREVIOUS_TAG"
            
            # Rollback ứng dụng
            cd /path/to/your/repository
            docker-compose down
            docker-compose up -d --build-arg IMAGE_TAG=$PREVIOUS_TAG
            echo "Rollback to version $PREVIOUS_TAG completed!"
