name: CI/CD Pipeline  # Tên của workflow này là "CI/CD Pipeline"

on:
  workflow_dispatch:  # Trigger workflow thủ công (thông qua giao diện GitHub)
    inputs:
      action:
        description: 'Select action to perform'  # Mô tả cho input người dùng
        required: true  # Yêu cầu người dùng chọn action
        default: 'build'  # Mặc định là 'build'
        type: choice  # Loại input là lựa chọn
        options:
          - build  # Lựa chọn 'build'
          - test  # Lựa chọn 'test'
          - deploy  # Lựa chọn 'deploy'
          - run-all  # Lựa chọn 'run-all' để chạy tất cả

jobs:
  # Job 'build': Chạy khi người dùng chọn 'build' hoặc 'run-all'
  build:
    if: ${{ github.event.inputs.action == 'build' || github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/your-image-name:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker push your-dockerhub-username/your-image-name:latest

  # Job 'test': Chạy khi người dùng chọn 'test' hoặc 'run-all'
  test:
    if: ${{ github.event.inputs.action == 'test' || github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    needs: build  # Đảm bảo job 'test' chỉ chạy sau khi job 'build' thành công
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."  # Thay thế bằng câu lệnh test thực tế

  # Job 'deploy': Chạy khi người dùng chọn 'deploy' hoặc 'run-all'
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' || github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    needs: test  # Đảm bảo job 'deploy' chỉ chạy sau khi job 'test' thành công
    steps:
      - name: SSH into Server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/repository
            git pull origin main
            docker-compose down
            docker-compose up -d
