name: CI/CD Pipeline  # Tên workflow

on:
  workflow_dispatch:  # Kích hoạt workflow thủ công
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'build'
        type: choice
        options:
          - build
          - test
          - deploy
          - run-all
          - rollback  # Tùy chọn rollback

jobs:
  # Job 'build': Xây dựng Docker image
  build:
    if: ${{ github.event.inputs.action == 'build' || github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t nhothoang/webezpdf:$timestamp .

      - name: Push Docker image to DockerHub
        run: |
          docker push nhothoang/webezpdf:$timestamp

  # Job 'test': Chạy các bài kiểm tra
  test:
    if: ${{ github.event.inputs.action == 'test' || github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          echo "Running tests..."
          # Thêm lệnh kiểm tra thực tế tại đây

  # Job 'deploy': Triển khai ứng dụng
  deploy:
    if: ${{ github.event.inputs.action == 'deploy' || github.event.inputs.action == 'run-all' }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: SSH into Server and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Deploying application..."
            cd /path/to/your/repository
            git pull origin main
            docker-compose down
            docker-compose up -d
            echo "Deployment completed!"

  # Job 'rollback': Khôi phục phiên bản trước
  rollback:
    if: ${{ github.event.inputs.action == 'rollback' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Server for Rollback
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e
            echo "Rolling back to previous version..."
            
            # Lấy tag của phiên bản trước
            PREVIOUS_TAG=$(docker images your-dockerhub-username/your-image-name --format '{{.Tag}}' | tail -n 2 | head -n 1)
            
            # Kiểm tra phiên bản trước
            if [ -z "$PREVIOUS_TAG" ]; then
              echo "No previous version found. Rollback failed!"
              exit 1
            fi
            
            echo "Found previous version: $PREVIOUS_TAG"
            
            # Rollback ứng dụng
            cd /path/to/your/repository
            docker-compose down
            docker-compose up -d --build-arg IMAGE_TAG=$PREVIOUS_TAG
            echo "Rollback to version $PREVIOUS_TAG completed!"
